"""empty message

Revision ID: 2511739747fc
Revises: 
Create Date: 2020-03-21 22:43:07.160435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2511739747fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_credentials_access_token'), 'spotify_credentials', ['access_token'], unique=True)
    op.create_index(op.f('ix_spotify_credentials_code'), 'spotify_credentials', ['code'], unique=True)
    op.create_index(op.f('ix_spotify_credentials_expires_at'), 'spotify_credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_spotify_credentials_refresh_token'), 'spotify_credentials', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_spotify_credentials_user_id'), 'spotify_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_credentials_user_id'), table_name='spotify_credentials')
    op.drop_index(op.f('ix_spotify_credentials_refresh_token'), table_name='spotify_credentials')
    op.drop_index(op.f('ix_spotify_credentials_expires_at'), table_name='spotify_credentials')
    op.drop_index(op.f('ix_spotify_credentials_code'), table_name='spotify_credentials')
    op.drop_index(op.f('ix_spotify_credentials_access_token'), table_name='spotify_credentials')
    op.drop_table('spotify_credentials')
    # ### end Alembic commands ###
